apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "employee-leave.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "employee-leave.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: employee-leave
  template:
    metadata:
      labels:
        app: employee-leave
        {{- include "employee-leave.labels" . | nindent 8 }}
    spec:
      containers:
        - name: employee-leave
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
