apiVersion: v1
kind: Service
metadata:
  name: employee-leave-service
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "employee-leave.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: employee-leave
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
