apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: employee-leave-management
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sharan-naidu/employee-leave-management.git
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: employee-leave

  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
